# @name get-all-users
GET http://localhost:3000/users

###

# @name get-all-projects
GET http://localhost:3000/projects

###

# @name get-all-organizations
GET http://localhost:3000/organizations

###

# @name get-project
GET http://localhost:3000/projects/673f39de96721779424c0082
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmlrdG9yIiwic3ViIjoiNjczZjRhMmM3ZTgzYzRhZDNjMzI1NzY1IiwiaWF0IjoxNzMyMjAxMDQ0LCJleHAiOjE3MzIyMDcwNDR9._W9F3LXj8qy1tkeMFAgJpkEbGpb5wpgA-7yvpTzrdc8

### 

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Viktor",
  "password": "123"
}


